version: "2"

services:
    halyard:
      container_name: halyard
      build:
        context: .
        dockerfile: halyard.dockerfile
      ports:
        - "8064:8064"
        - "8084:8084"
        - "9000:9000"
      volumes:
        - .:/var/udemy/advanced-kubernetes-course
        - ~/.kube:/root/.kube
        - ~/.helm:/root/.helm
        - ~/.hal:/root/.hal
      working_dir: /var/udemy/advanced-kubernetes-course
      extra_hosts:
        - "local.docker.com:192.168.99.100"
      environment:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    helm-kubectl:
      container_name: helm-kubectl
      build: 
        context: .
        dockerfile: helm-kubectl.dockerfile
      ports:
        - "9000:9000"
      volumes:
        - .:/var/udemy/advanced-kubernetes-course
        - ~/.kube:/root/.kube
        - ~/.helm:/root/.helm
      working_dir: /var/udemy/advanced-kubernetes-course
      extra_hosts:
        - "local.docker.com:192.168.99.100"
 