apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret
spec:
  containers:
  - image: mysql:5.5
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: foobar
          key: password
    imagePullPolicy: IfNotPresent
    name: mysql
  restartPolicy: Always
