apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      name: webui
      nodePort: 30100
  selector:
    name: grafana
