apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-exporter
    namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
  name: node-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
  selector:
    name: node-exporter
