apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
  namespace: oreilly
  selfLink: /api/v1/namespaces/default/services/mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
