apiVersion: v1
kind: Pod
metadata:
  name: pawn
spec:
  containers:
  - image: busybox
    command:
    - sleep
    - "3600"
    name: pawn
    securityContext:
      privileged: true
  hostNetwork: true
  hostPID: true
  restartPolicy: Always
