apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  replicas: 4
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jenkins-world
    spec:
      containers:
      - name: jenkins-pod
        image:  jenkins:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000