apiVersion: v1
kind: Service
metadata:
  name: buffalo-hello-go-svc
  labels:
    app: buffalo-hello-go-world
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    nodePort: 30002
    protocol: TCP
  selector:
    app: buffalo-hello-go-world