apiVersion: batch/v1
kind: Job
metadata:
  name: job1
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    spec:
      containers:
      - name: post-install
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh','-c','echo post-install Job is running ; sleep 5']
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1