apiVersion: v1
kind: Pod
metadata:
  name: init-demo2
spec:
  containers:
  - name: python
    image: python:2.7-alpine
    command:
      - python
      - "-m"
      - SimpleHTTPServer
    volumeMounts:
    - name: path
      mountPath: /tmp/init
  initContainers:
  - name: busybox
    image: busybox
    command:
    - wget
    - "-O"
    - "/tmp/init/index.html"
    - http://google.com 
    volumeMounts:
    - name: path
      mountPath: /tmp/init
  volumes:
  - name: path
    emptyDir: {}
