apiVersion: v1
kind: Pod
metadata:
  name: 2-pod-nginx
spec:
  containers:
  - name: nginx1
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: nginx2
    image: nginx:latest
    env:
    - name: NGINX_PORT
      value: "8080"
    ports:
    - containerPort: 8080