kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: meetup
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"] # You can also use ["*"]
