provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  go-echo:
    lang: golang-http
    handler: ./go-echo
    image: rcampbell/go-echo:latest
    environment:
      write_debug: true
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1

