version: '2'
 
services:
    # db:
    #   container_name: db
    #   build:
    #     context: .
    #     dockerfile: ./.docker/mysql.dockerfile
    #   restart: always
    #   environment:
    #     MYSQL_ROOT_PASSWORD: bamboo
    #     MYSQL_DATABASE: bamboo
    #     MYSQL_USER: bamboo
    #     MYSQL_PASSWORD: bamboo
    #   volumes:
    #     - ./db_data:/var/lib/mysql
    #   ports:
    #   - 3306:3306
    bamboo-server:
      # depends_on: 
      #   - db
      container_name: bamboo-server
      build:
        context: .
        dockerfile: ./.docker/bamboo.dockerfile
      working_dir: /var/app
      ports:
      - "80:80"
      volumes:
        - .:/var/app
      command:  >
          /bin/sh -c "
          cd atlassian-bamboo-6.6.2 &&
          bin/start-bamboo.sh -fg"
    bamboo-agent:
      # depends_on: 
      #   - db
      container_name: bamboo-agent
      build:
        context: .
        dockerfile: ./.docker/bamboo.dockerfile
      working_dir: /var/app
      ports:
      - "80:80"
      volumes:
        - .:/var/app
      command:  >
          /bin/sh -c "
          cd atlassian-bamboo-6.6.2 &&
          bin/start-bamboo.sh -fg"
# volumes:
#     db_data:
#       driver: "local"