apiVersion: v1
kind: Pod
metadata:
  name: busybox-to-amd64
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  nodeSelector:
    beta.kubernetes.io/arch: amd64
