apiVersion:   v1
kind:         Pod
metadata:
  name:       nginx-jumpod
  labels:
    app: nginx-jumpod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name:     shell
    image:    centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"