apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: date
spec:
    schedual: "*/1 * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                    - name: dateperminute
                        image: busybox
                        args:
                        - /bin/sh
                        - -c
                        - datei; sleep 30
                    restartPolicy: OnFailure