version: "2"

services:
    class:
      container_name: class
      build:
        context: .
        dockerfile: class.dockerfile
      volumes:
        - .:/var/work
        - ~/.gsutil:/root/.gsutil
        - ~/.config:/root/.config
      working_dir: /var/work
      environment:
        - PATH=$PATH:/root/google-cloud-sdk/bin
      extra_hosts:
        - "local.docker.com:192.168.99.100"
 