apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubernetes.io/change-cause: kubectl set image deployment/ghost ghost=ghost:09
      --all=true
  creationTimestamp: 2018-03-18T09:12:06Z
  generation: 3
  labels:
    run: ghost
  name: ghost
  namespace: default
  resourceVersion: "838203"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ghost
  uid: 6dff1291-2a8c-11e8-b682-12b2b3102ff4
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ghost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ghost
    spec:
      containers:
      - image: ghost:09
        imagePullPolicy: Always
        name: ghost
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-03-18T09:12:06Z
    lastUpdateTime: 2018-03-18T09:12:06Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
