apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-one
  labels:
    system: secondary
  namespace: accounting
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
      nodeSelector:
        system: secondOne
---
apiVersion: v1
kind: Service
metadata:
  labels:
    system: secondary
  name: nginx-one
  namespace: accounting
spec:
  ports:
  - port: 80
    # protocol: TCP
    # targetPort: 8080
  selector:
    app: nginx
  type: ClusterIP
