apiVersion: v1
kind: Pod
metadata:
    name: yamlpod
    namespace: default
    labels:
        name: exampleyamlpod
spec: 
    containers:
    - image: nginx
      name: nginx
      ports: 
      - containerPort: 80