apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-one
  # volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi