# apiVersion: storage.k8s.io/v1beta1
# kind: StorageClass
# metadata:
#   name: standard
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
#   zone: us-east-1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:  Recycle
  nfs:
    path: /opt/sfw
    server: fs-5d9b5015.efs.us-east-1.amazonaws.com
    readOnly: false
    # aws efs create-file-system --creation-token 1
    # aws efs create-mount-target --file-system-id fs-5d9b5015 --subnet-id subnet-1202223d --security-groups sg-ecaa0a9a