apiVersion: v1
kind: Pod
metadata:
  name: hello-go-pod
  labels:
    app: hello-go
spec:
  containers:
  - name: k8s-demo
    image: rcampbell/hello_go
    ports:
    - name: hello-go-port
      containerPort: 3000
