apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: wordpress
  name: wordpress
  namespace: oreilly
  selfLink: /api/v1/namespaces/default/services/wordpress
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wordpress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
